[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog-post"
  to = "/blog-post.html"
  status = 200

[[redirects]]
  from = "/project"
  to = "/project.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
